version: '3'

services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: container_mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - '3308:3306'
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mynetwork
    expose:
      - '3306'

networks:
  mynetwork:
    driver: bridge