version: '3'

services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile_mysql
    restart: always
    container_name: container_mysql_f
    hostname: host_mysql_f
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3310:3306"
    volumes:
      - ./sql/init_mysql.sql:/docker-entrypoint-initdb.d/init_mysql.sql
    networks:
      - mynetwork
    expose:
      - '3306'


  postgres:
    build:
      context: .
      dockerfile: Dockerfile_postgres
    restart: always
    container_name: container_postgres_f
    hostname: host_postgres_f
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - ./sql/init_postgres.sql:/docker-entrypoint-initdb.d/init_postgres.sql
    networks:
      - mynetwork
    expose:
      - '5432'

networks:
  mynetwork:
    driver: bridge