version: '3'

services:
  mysql:
    image: mysql:8.2
    restart: always
    container_name: container_mysql_f
    hostname: host_mysql_f
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_LOCAL_PORT}:${MYSQL_DOCKER_PORT}"
    volumes:
      - ./sql/init_mysql.sql:/docker-entrypoint-initdb.d/init_mysql.sql
    networks:
      - mynetwork
    expose:
      - '${MYSQL_DOCKER_PORT}'


  postgres:
    image: postgres:16.1
    restart: always
    container_name: container_postgres_f
    hostname: host_postgres_f
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_LOCAL_PORT}:${POSTGRES_DOCKER_PORT}"
    volumes:
      - ./sql/init_postgres.sql:/docker-entrypoint-initdb.d/init_postgres.sql
    networks:
      - mynetwork
    expose:
      - '${POSTGRES_DOCKER_PORT}'

networks:
  mynetwork:
    driver: bridge