version: '2.23'

services:

  db:
    image: postgres:16.1
    restart: always
    container_name: container_psql
    hostname: host_psql
    env_file:
      - .env
    volumes:
      - ./sql/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
      - ./sql/data.sql:/docker-entrypoint-initdb.d/data.sql
    ports:
      - "${POSTGRES_LOCAL_PORT}:${POSTGRES_DOCKER_PORT}"
    networks:
      - mynetwork
    expose:
      - '${POSTGRES_DOCKER_PORT}'

networks:
  mynetwork:
    driver: bridge
