version: '2.23'

services:

  db:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: container_psql
    hostname: host_psql
    env_file:
      - .env
    volumes:
      - ./sql/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
      - ./sql/data.sql:/docker-entrypoint-initdb.d/data.sql
    ports:
      - "5432:5432"
    networks:
      - mynetwork
    expose:
      - '5432'

networks:
  mynetwork:
    driver: bridge
